FROM node:22-alpine

WORKDIR /app

RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/main" > /etc/apk/repositories \
    && echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/community" >> /etc/apk/repositories \
    && apk update

RUN apk add --no-cache postgresql15-client openssl

COPY package*.json ./
RUN npm install

COPY . .

RUN chmod -R 777 /app/node_modules/.prisma || true

ENV NODE_ENV=development
EXPOSE 3000

CMD ["sh", "-c", "npm run dev"]
