# syntax=docker/dockerfile:1.4

FROM node:22-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=development
EXPOSE 3000

COPY scripts/init-db.sh /usr/src/app/scripts/init-db.sh
ENTRYPOINT ["sh", "/usr/src/app/scripts/init-db.sh"]

CMD ["npm", "run", "start:dev"]
