# syntax=docker/dockerfile:1.4

FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
RUN npx prisma generate

# --- Stage de execução ---
FROM node:22-alpine AS runner

WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY ormconfig.ts ./
ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "dist/main.js"]
